/**
 * OpenClaw plugin entry point for context-shunt.
 *
 * Wiring, verified against the OpenClaw checkout named by `CONTEXT_SHUNT_OPENCLAW_ROOT`:
 *
 * - `api.on("before_tool_call", handler)` runs before the tool executes and a
 *   `{ block: true }` result short-circuits it. That is what makes the large-read gate a
 *   pre-execution gate: a blocked read never runs. The host fails this hook closed on
 *   timeout, which matches what the gate needs.
 * - `api.runtime.llm.complete` with `execution.mode: "isolated-agent-runtime"` runs a
 *   literal-zero-tool completion with no inherited conversation and no tools
 *   (`src/plugins/runtime/runtime-llm-isolated.ts`). That is the reader's only model path.
 * - `api.registerTool` exposes the three read-only escape hatches. No writer tool is
 *   registered, and `openclaw.plugin.json` declares each name in `contracts.tools`.
 *
 * Session lifecycle, grounded in the host's own reason enum
 * --------------------------------------------------------
 * `session_end` is not a single event on OpenClaw. `PluginHookSessionEndEvent.reason`
 * (`src/plugins/hook-types.ts`) is one of new / reset / idle / daily / compaction / deleted
 * / shutdown / restart / unknown, and **compaction fires mid-conversation**: the session id
 * rotates while the same conversation continues. Revoking handles there would delete
 * exactly the recovery state the next turn needs, which is the moment the shunt matters
 * most.
 *
 * So handles are scoped by `sessionKey` - stable across a session-id rotation - with the
 * `sessionId` as the generation, and teardown is decided by the reason:
 *
 * - new / reset / deleted -> the user cleared the conversation: revoke.
 * - compaction / idle / daily / shutdown / restart / unknown -> keep, and let TTL bound it.
 *
 * Provenance
 * ----------
 * OpenClaw's isolated completion returns the host's own post-policy selection
 * (`selection.provider` / `selection.modelId` threaded through
 * `runIsolatedAgentRuntimeCompletion`), which is a genuine routing fact - so it is reported
 * as `resolved_*` and the attribution comes back `resolved`. It is *not* a provider
 * confirmation that those tokens were generated by that model, so this adapter never claims
 * `actual`. Usage may be absent: `src/agents/isolated-completion.ts` says in as many words
 * that "CLI runtimes may not report token usage; absence must not be projected as zero", so
 * an absent count is passed through as absent and the reader falls back to a named estimate.
 *
 * The optional oversized post-tool mode is deliberately not wired: see `src/capability.ts`
 * for the host-source evidence, and `docs/capability-matrix.md` for the operator-facing
 * table.
 */
import { homedir } from "node:os";
import { join } from "node:path";

import {
  type CapabilityReport,
  type Config,
  EMITTED_SCHEMA_VERSION,
  type Envelope,
  type GateDecision,
  buildProvider,
  type ReaderProvider,
  ScopeIdentity,
  ShuntError,
  ShuntSession,
  SnapshotStore,
  UnavailableProvider,
  errorEnvelope,
  enforceOrFixed,
  fixedError,
  isShuntError,
  loadConfig,
  modeEnabled,
  reportToJson,
  validateToolArgs,
} from "@context-shunt/core";

import { buildCapabilityReport } from "./src/capability.js";
import { normalizeToolCall, requestIdFrom } from "./src/normalize.js";

export const PLUGIN_ID = "context-shunt";

/** Session-end reasons that mean the user actually cleared the conversation. */
const DESTRUCTIVE_END_REASONS = new Set(["new", "reset", "deleted"]);

/** The subset of the host plugin API this adapter uses. */
export interface OpenClawPluginApi {
  on(
    hook: string,
    handler: (event: Record<string, unknown>, ctx?: Record<string, unknown>) => unknown,
    opts?: Record<string, unknown>,
  ): void;
  registerTool?(
    tool:
      | Record<string, unknown>
      | ((ctx: Record<string, unknown>) => Record<string, unknown> | null | undefined),
    opts?: { name?: string; names?: string[]; optional?: boolean },
  ): void;
  pluginConfig?: Record<string, unknown>;
  logger?: {
    info(msg: string, ...rest: unknown[]): void;
    warn?(msg: string, ...rest: unknown[]): void;
  };
  runtime?: {
    version?: string;
    llm?: {
      complete(opts: {
        messages: [{ role: "user"; content: string }];
        systemPrompt: string;
        model: string;
        maxTokens?: number;
        temperature?: number;
        signal?: AbortSignal | undefined;
        purpose?: string;
        execution: { mode: "isolated-agent-runtime"; timeoutMs: number };
      }): Promise<{
        text?: string;
        provider?: string;
        model?: string;
        agentId?: string;
        usage?: {
          inputTokens?: number;
          outputTokens?: number;
          cacheReadTokens?: number;
          totalTokens?: number;
        };
        execution?: { mode?: string; owner?: { kind?: string; id?: string } };
      }>;
    };
  };
}

const DEFAULT_HOOKS = [
  "before_tool_call",
  "after_tool_call",
  "tool_result_persist",
  "before_message_write",
  "session_start",
  "session_end",
] as const;

export const READER_TOOL_NAME = "context_shunt_read";
export const INSPECT_TOOL_NAME = "context_shunt_inspect";
export const STATS_TOOL_NAME = "context_shunt_stats";

export const READER_TOOL_DESCRIPTION =
  "Answer a question about one or more large files without pulling them into this "
  + "conversation. Returns a bounded, citation-verified answer that is generated by a reader "
  + "model, not raw source text. Read-only. Pass paths for a first look, or handles to ask a "
  + "sharper question about a snapshot you already hold.";

export const READER_TOOL_PARAMETERS = {
  type: "object",
  additionalProperties: false,
  properties: {
    question: { type: "string", description: "The question to answer. Required." },
    paths: {
      type: "array",
      items: { type: "string" },
      description:
        "Absolute paths inside a configured workspace root. Use this OR handles, never both.",
    },
    handles: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: { source_id: { type: "string" }, snapshot_id: { type: "string" } },
        required: ["source_id", "snapshot_id"],
      },
      description:
        "Handles from an earlier reply, to refine the question against the same immutable "
        + "snapshot. Use this OR paths, never both.",
    },
  },
  required: ["question"],
} as const;

export const INSPECT_TOOL_DESCRIPTION =
  "Return exact text from a snapshot you already hold: a line range, a byte range, or "
  + "literal-search hits. Deterministic - no model is involved, so the result is source bytes "
  + "rather than a summary. Each page is capped at 16 KiB and counts against a cumulative "
  + "disclosure budget, so a large file cannot be paged into a full copy; a file small "
  + "enough to fit that budget can be returned in full.";

export const INSPECT_TOOL_PARAMETERS = {
  type: "object",
  additionalProperties: false,
  properties: {
    source_id: { type: "string", description: "Handle from an earlier reply." },
    snapshot_id: {
      type: "string",
      description: "The snapshot hash you were given. A mismatch is refused.",
    },
    selector: {
      type: "object",
      description:
        'Exactly one of {"kind":"lines","start":N,"end":N}, {"kind":"bytes","start":N,"end":N}, '
        + 'or {"kind":"search","needle":"...","max_matches":N}.',
    },
    cursor: {
      type: "string",
      description: "Opaque next_cursor from a previous inspect result.",
    },
  },
  required: ["source_id", "snapshot_id", "selector"],
} as const;

export const STATS_TOOL_DESCRIPTION =
  "Report this session's context-shunt accounting: bytes withheld, tokens saved or spent, "
  + "and per-operation records. Read-only - it cannot reset a counter, change retention, see "
  + "another session, or reveal any source content.";

export const STATS_TOOL_PARAMETERS = {
  type: "object",
  additionalProperties: false,
  properties: {
    page: { type: "integer", description: "1-based page of operation records." },
    page_size: { type: "integer", description: "Records per page, at most 8." },
  },
  required: [],
} as const;

export class ContextShuntPlugin {
  private readonly sessions = new Map<string, ShuntSession>();
  private readonly generations = new Map<string, number>();
  private readonly store: SnapshotStore;
  readonly config: Config;
  readonly capability: CapabilityReport;

  constructor(
    private readonly api: OpenClawPluginApi,
    opts: { defaultCacheDir?: string } = {},
  ) {
    const raw = { ...(api.pluginConfig ?? {}) } as Record<string, unknown>;
    const cacheDir =
      opts.defaultCacheDir
      ?? process.env["CONTEXT_SHUNT_CACHE"]
      ?? join(homedir(), ".cache", "context-shunt");
    this.config = loadConfig(raw as never, cacheDir);
    this.capability = buildCapabilityReport({
      hooks: DEFAULT_HOOKS,
      hasModelBridge: typeof api.runtime?.llm?.complete === "function",
      hostVersion: api.runtime?.version ?? "",
      readerModel: this.config.readerModel,
    });
    this.store = new SnapshotStore(this.config.spillDir, this.config.limits);
    // Deterministic recovery first: clear staged temps and unreferenced content from a
    // previous crash before any new handle is published.
    try {
      this.store.recover();
    } catch (err) {
      if (!isShuntError(err)) throw err;
    }
  }

  /** Registers only what the capability probe proved. */
  register(): void {
    if (modeEnabled(this.capability, "local_gate")) {
      this.api.on("before_tool_call", (event, ctx) => this.onBeforeToolCall(event, ctx));
    }
    this.api.on("session_end", (event) => this.onSessionEnd(event));
    if (typeof this.api.registerTool === "function") {
      if (modeEnabled(this.capability, "reader")) {
        this.api.registerTool((ctx) => this.readerTool(ctx), { name: READER_TOOL_NAME });
      }
      if (this.config.inspectEnabled && modeEnabled(this.capability, "deterministic_inspect")) {
        this.api.registerTool((ctx) => this.inspectTool(ctx), { name: INSPECT_TOOL_NAME });
      }
      if (this.config.statsEnabled && modeEnabled(this.capability, "session_stats")) {
        this.api.registerTool((ctx) => this.statsTool(ctx), { name: STATS_TOOL_NAME });
      }
    }
    this.api.logger?.info(
      `context-shunt capability report: ${JSON.stringify(reportToJson(this.capability))}`,
    );
  }

  /** Veto an oversized or unprovable read before the tool runs. */
  onBeforeToolCall(
    event: Record<string, unknown>,
    ctx?: Record<string, unknown>,
  ): { block: true; blockReason: string } | undefined {
    if (!this.config.gateEnabled) return undefined;
    const params = event?.params;
    const { tool, args } = normalizeToolCall(
      String(event?.toolName ?? ""),
      typeof params === "object" && params !== null
        ? (params as Record<string, unknown>)
        : undefined,
    );
    if (tool === "other") return undefined;
    const session = this.session(scopeKeyOf(ctx, event));
    let decision: GateDecision;
    try {
      decision = session.evaluateToolCall(tool, args);
    } catch {
      // Fail closed for a read-like call we could not evaluate.
      return {
        block: true,
        blockReason: serialize(
          session.blockEnvelope(requestIdFrom(event?.toolCallId), {
            decision: "blocked",
            form: "unclassifiable",
            code: "HOST_UNSAFE",
            reason: "GATE_ERROR",
          }),
        ),
      };
    }
    if (decision.decision !== "blocked") return undefined;
    return {
      block: true,
      blockReason: serialize(session.blockEnvelope(requestIdFrom(event?.toolCallId), decision)),
    };
  }

  /**
   * The registered tool objects. `execute(toolCallId, params)` is the host's shape, and the
   * bounded envelope is returned as a single text content block.
   */
  readerTool(toolContext: Record<string, unknown> = {}): Record<string, unknown> {
    return {
      name: READER_TOOL_NAME,
      description: READER_TOOL_DESCRIPTION,
      parameters: READER_TOOL_PARAMETERS,
      execute: async (toolCallId: string, params: unknown, signal?: AbortSignal) => {
        const text = await this.onReaderTool(params, { ...toolContext, toolCallId, signal });
        return { content: [{ type: "text", text }] };
      },
    };
  }

  inspectTool(toolContext: Record<string, unknown> = {}): Record<string, unknown> {
    return {
      name: INSPECT_TOOL_NAME,
      description: INSPECT_TOOL_DESCRIPTION,
      parameters: INSPECT_TOOL_PARAMETERS,
      execute: (toolCallId: string, params: unknown) => ({
        content: [
          { type: "text", text: this.onInspectTool(params, { ...toolContext, toolCallId }) },
        ],
      }),
    };
  }

  statsTool(toolContext: Record<string, unknown> = {}): Record<string, unknown> {
    return {
      name: STATS_TOOL_NAME,
      description: STATS_TOOL_DESCRIPTION,
      parameters: STATS_TOOL_PARAMETERS,
      execute: (toolCallId: string, params: unknown) => ({
        content: [
          { type: "text", text: this.onStatsTool(params, { ...toolContext, toolCallId }) },
        ],
      }),
    };
  }

  /**
   * Answer a question about a source. Read-only.
   *
   * Exactly one source form: `paths` for an initial capture, or `handles` for a refined
   * question over snapshots the caller already holds.
   */
  async onReaderTool(input: unknown, ctx?: Record<string, unknown>): Promise<string> {
    const session = this.session(scopeKeyOf(ctx));
    const requestId = requestIdFrom(ctx?.["toolCallId"] ?? "reader");

    let args: Record<string, unknown>;
    try {
      args = validateToolArgs(readerArgs(input));
    } catch (err) {
      if (!isShuntError(err)) throw err;
      return serialize(enforceOrFixed(errorEnvelope(requestId, err), this.config.limits));
    }

    let sources: Array<Record<string, unknown>>;
    let refined = false;
    try {
      if (Array.isArray(args["paths"])) {
        const entries = session.registerPaths((args["paths"] as string[]).map(String));
        sources = entries.map((entry) => ({
          source_id: entry.sourceId,
          snapshot_id: entry.snapshot.snapshotId,
          selector: args["selector"] ?? { kind: "all" },
        }));
      } else {
        refined = true;
        sources = (args["handles"] as Array<Record<string, string>>).map((handle) => ({
          source_id: handle["source_id"],
          snapshot_id: handle["snapshot_id"],
          selector: args["selector"] ?? { kind: "all" },
        }));
      }
    } catch (err) {
      if (!isShuntError(err)) return serialize(fixedError(requestId, "STORE_FAILED"));
      return serialize(enforceOrFixed(errorEnvelope(requestId, err), this.config.limits));
    }

    const request: Record<string, unknown> = {
      schema_version: EMITTED_SCHEMA_VERSION,
      request_id: requestId,
      operation: "read",
      question: args["question"],
      sources,
      budgets: {
        max_chunks: this.config.limits.maxChunksPerRequest,
        max_answer_bytes: this.config.limits.maxAnswerBytes,
        deadline_ms: this.config.limits.requestDeadlineMs,
      },
    };
    if (refined) request["refined"] = true;
    const signal = ctx?.["signal"] instanceof AbortSignal ? ctx["signal"] : undefined;
    return serialize(await session.read(request, signal));
  }

  /** Exact lines, bytes or literal-search hits from a handle. Zero model calls. */
  onInspectTool(input: unknown, ctx?: Record<string, unknown>): string {
    const session = this.session(scopeKeyOf(ctx));
    const requestId = requestIdFrom(ctx?.["toolCallId"] ?? "inspect");
    const raw = (typeof input === "object" && input !== null ? input : {}) as Record<string, unknown>;

    let args: Record<string, unknown>;
    try {
      args = validateToolArgs({
        tool: INSPECT_TOOL_NAME,
        ...Object.fromEntries(
          (["source_id", "snapshot_id", "selector", "cursor"] as const)
            .filter((key) => raw[key] !== undefined)
            .map((key) => [key, raw[key]]),
        ),
      });
    } catch (err) {
      if (!isShuntError(err)) throw err;
      return serialize(enforceOrFixed(errorEnvelope(requestId, err), this.config.limits));
    }

    const request: Record<string, unknown> = {
      schema_version: EMITTED_SCHEMA_VERSION,
      request_id: requestId,
      operation: "inspect",
      source_id: args["source_id"],
      snapshot_id: args["snapshot_id"],
      selector: args["selector"],
      budgets: {
        max_result_bytes: Math.min(
          Number(raw["max_result_bytes"] ?? this.config.limits.inspectMaxResultBytes),
          this.config.limits.inspectMaxResultBytes,
        ),
        max_scan_lines: Math.min(
          Number(raw["max_scan_lines"] ?? this.config.limits.inspectMaxScanLines),
          this.config.limits.inspectMaxScanLines,
        ),
      },
    };
    if (args["cursor"] !== undefined) request["cursor"] = args["cursor"];
    return serialize(session.inspect(request));
  }

  /** This session's own bounded accounting. Read-only; resets nothing. */
  onStatsTool(input: unknown, ctx?: Record<string, unknown>): string {
    const session = this.session(scopeKeyOf(ctx));
    const requestId = requestIdFrom(ctx?.["toolCallId"] ?? "stats");
    const raw = (typeof input === "object" && input !== null ? input : {}) as Record<string, unknown>;
    const request: Record<string, unknown> = {
      schema_version: EMITTED_SCHEMA_VERSION,
      request_id: requestId,
      operation: "stats",
    };
    for (const key of ["page", "page_size"] as const) {
      if (raw[key] !== undefined) request[key] = Number(raw[key]);
    }
    return serialize(session.stats(request));
  }

  /**
   * Decide teardown from the host's own reason enum.
   *
   * `compaction` rotates the session id while the conversation continues, so revoking there
   * would destroy the recovery handles the next turn needs. Only an explicit clear revokes;
   * everything else relies on TTL and the opportunistic sweep.
   */
  onSessionEnd(event: Record<string, unknown>): void {
    const key = scopeKeyOf(undefined, event);
    const session = this.sessions.get(key);
    if (!session) return;
    const reason = String(event?.["reason"] ?? "unknown");
    if (!DESTRUCTIVE_END_REASONS.has(reason)) {
      session.endTurn();
      return;
    }
    session.close();
    this.sessions.delete(key);
    // A cleared conversation starts a new generation, so an old handle cannot be replayed.
    this.generations.set(key, (this.generations.get(key) ?? 1) + 1);
  }

  capabilityJson(): Record<string, unknown> {
    return reportToJson(this.capability);
  }

  private session(key: string): ShuntSession {
    let session = this.sessions.get(key);
    if (!session) {
      session = new ShuntSession(key, this.config, this.capability, {
        provider: this.provider(),
        store: this.store,
        identity: new ScopeIdentity({
          host: "openclaw",
          profile: PLUGIN_ID,
          principal: "local",
          session: key,
          generation: this.generations.get(key) ?? 1,
        }),
      });
      this.sessions.set(key, session);
    }
    return session;
  }

  private provider(): ReaderProvider {
    const llm = this.api.runtime?.llm;
    if (!llm || typeof llm.complete !== "function") {
      return new UnavailableProvider("HOST_LLM_UNAVAILABLE");
    }
    // `buildProvider` assembles the primary *and* the configured availability fallback
    // chain. Constructing `HostBridgeProvider` directly here meant `reader.fallback_chain`
    // parsed, validated and documented - and then did nothing at all, so a deployment that
    // configured a fallback silently had none.
    return buildProvider(
      this.config,
      async ({ system, user, provider, model, maxOutputTokens, timeoutMs, signal }) => {
        // The host owns credentials and routing; provider exception text is dropped by
        // HostBridgeProvider so only MODEL_ERROR crosses back.
        //
        // The route comes from *this candidate's* provider. Building it from
        // `config.readerProvider` instead sent every fallback to the primary's provider
        // under the fallback's model name, so a chain onto a different provider silently
        // asked the wrong one for a model it does not serve. `openai` remains the default
        // only when nothing has been pinned at all.
        const result = await llm.complete({
          messages: [{ role: "user", content: user }],
          systemPrompt: system,
          model: `${provider || this.config.readerProvider || "openai"}/${model}`,
          maxTokens: maxOutputTokens,
          temperature: 0,
          signal,
          purpose: "context-shunt-reader",
          execution: { mode: "isolated-agent-runtime", timeoutMs },
        });
        const usage = result.usage;
        return {
          text: result.text ?? "",
          // The host reports its own post-policy selection, which is a routing fact rather
          // than a provider confirmation - so it is `resolved`, never `reported`.
          resolved_provider: result.provider,
          resolved_model: result.model,
          provider_confirms_generation: false,
          // "CLI runtimes may not report token usage; absence must not be projected as
          // zero" - src/agents/isolated-completion.ts. Absent stays absent.
          input_tokens: usage?.inputTokens,
          output_tokens: usage?.outputTokens,
          cache_tokens: usage?.cacheReadTokens,
          usage_exact: usage?.inputTokens !== undefined && usage?.outputTokens !== undefined,
        };
      },
    );
  }
}

function readerArgs(input: unknown): Record<string, unknown> {
  const raw = (typeof input === "object" && input !== null ? input : {}) as Record<string, unknown>;
  const out: Record<string, unknown> = { tool: READER_TOOL_NAME, question: raw["question"] };
  const paths = typeof raw["paths"] === "string" ? [raw["paths"]] : raw["paths"];
  if (paths !== undefined) out["paths"] = paths;
  if (raw["handles"] !== undefined) out["handles"] = raw["handles"];
  if (raw["selector"] !== undefined) out["selector"] = raw["selector"];
  return out;
}

/**
 * Scope handles by `sessionKey`, not `sessionId`.
 *
 * A compaction rotates the session id while the conversation continues, so keying on the id
 * would silently orphan every handle at exactly the point the shunt is most useful. The key
 * is stable across that rotation; the id becomes the generation instead.
 */
function scopeKeyOf(
  ctx?: Record<string, unknown>,
  event?: Record<string, unknown>,
): string {
  for (const candidate of [
    ctx?.["sessionKey"],
    event?.["sessionKey"],
    ctx?.["sessionId"],
    event?.["sessionId"],
  ]) {
    if (typeof candidate === "string" && candidate.length > 0) return candidate;
  }
  return "unbound";
}

function serialize(envelope: Envelope | Record<string, unknown>): string {
  return JSON.stringify(envelope);
}

/** OpenClaw plugin entry. */
export default {
  id: PLUGIN_ID,
  name: "Context Shunt",
  description: "Read-only large-source gate, question-driven reader and exact inspector.",
  register(api: OpenClawPluginApi): void {
    try {
      new ContextShuntPlugin(api).register();
    } catch (err) {
      // A refused configuration (writer.enabled, a widened cap, a bad attribution policy)
      // must stop the plugin loudly rather than load a half-configured gate.
      const code = isShuntError(err) ? (err as ShuntError).code : "INVALID_REQUEST";
      api.logger?.warn?.(`context-shunt refused to load: ${code}`);
      throw err;
    }
  },
};
